| 2023-01-08 00:33:25,540 – [INFO]: Попытка подключения к postgres. Исполняемый файл – 'postgres_client.py': функция – 'connect'(29)
| 2023-01-08 00:33:25,668 – [INFO]: Успешное подключение к postgres. Исполняемый файл – 'postgres_client.py': функция – 'connect'(33)
| 2023-01-08 00:33:25,668 – [INFO]: Попытка подключения к Elasticsearch. Исполняемый файл – 'elasticsearch_client.py': функция – 'connect'(35)
| 2023-01-08 00:33:25,682 – [INFO]: Подключение к Elasticsearch: True. Исполняемый файл – 'elasticsearch_client.py': функция – 'connect'(37)
| 2023-01-08 00:33:26,402 – [DEBUG]: Индекс movies создан. Ответ Elasticsearch: {'acknowledged': True, 'shards_acknowledged': True, 'index': 'movies'}. Исполняемый файл – 'helpers.py': функция – 'create_index_if_not_exists'(38)
| 2023-01-08 00:33:26,420 – [DEBUG]: Создан новый курсор для Postgres. Исполняемый файл – 'postgres_client.py': функция – 'connect'(78)
| 2023-01-08 00:33:26,420 – [DEBUG]: Файл /Users/madihanagatanov/middle_code/new_admin_panel_sprint_3/etl/state/state.json не может быть прочитан. Произошла ошибка: [Errno 2] No such file or directory: '/Users/madihanagatanov/middle_code/new_admin_panel_sprint_3/etl/state/state.json'.. Исполняемый файл – 'storage.py': функция – 'retrieve_state'(45)
| 2023-01-08 00:33:26,580 – [DEBUG]: Файл /Users/madihanagatanov/middle_code/new_admin_panel_sprint_3/etl/state/state.json не может быть прочитан. Произошла ошибка: [Errno 2] No such file or directory: '/Users/madihanagatanov/middle_code/new_admin_panel_sprint_3/etl/state/state.json'.. Исполняемый файл – 'storage.py': функция – 'retrieve_state'(45)
| 2023-01-08 00:33:26,582 – [INFO]: Успешно загружено 100 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:26,982 – [INFO]: Успешно загружено 200 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:28,092 – [INFO]: Успешно загружено 300 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:29,206 – [INFO]: Успешно загружено 400 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:30,266 – [INFO]: Успешно загружено 500 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:31,316 – [INFO]: Успешно загружено 600 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:32,375 – [INFO]: Успешно загружено 700 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:33,433 – [INFO]: Успешно загружено 800 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:34,487 – [INFO]: Успешно загружено 900 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:35,550 – [INFO]: Успешно загружено 999 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-08 00:33:35,550 – [ERROR]: Произошла ошибка при валидации фильмов из PostgreSQL. ['e72208b6-7181-49eb-9c25-2bc54629b21d']. Подробности: etl_status/state.json. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(31)
| 2023-01-08 00:33:36,602 – [DEBUG]: Postgres cursor закрыт. Исполняемый файл – 'postgres_client.py': функция – 'close'(93)
| 2023-01-08 00:33:36,605 – [INFO]: Соединение закрыто для ElasticsearchClient. Исполняемый файл – 'base_client.py': функция – 'close'(60)
| 2023-01-08 00:33:36,605 – [INFO]: Соединение закрыто для PostgresClient. Исполняемый файл – 'base_client.py': функция – 'close'(60)
| 2023-01-08 00:33:36,606 – [INFO]: Остановка процесса на 5 минут. Исполняемый файл – 'main.py': функция – 'main'(18)
